### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by netalex** [oncomouse/gulp-pandoc-writer#8]
`"gulp-pandoc-writer": "^1.0.3"`
this error 
```
Error: write EPIPE
    at _errnoException (util.js:1021:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:860:14)
```
on this conf

```javascript
//pandoc md 2 html
gulp.task('md2html', function(){
  gulp.src('src/master/**/*.md')
  .pipe(pandocWriter({
    outputDir:'dist/output/',
    inputFileType:'.md',
    outputFileType: '.html',
    args: [`--css ${DIST_DIR}/css/main.css`]
  }))
  //.pipe(gulp.dest(`${DIST_DIR}`))
});
```

**Comment by oncomouse** [comment]
There's an error in your configuration file that appears to be causing the error:

Per the [Pandoc Manual](https://pandoc.org/MANUAL.html), the option should be `--css=${DIST_DIR}/css/main.css` (with an equals sign).

It worked for me after that.
